add a profile for building the server-app
```
mvn package -P server-app
```

get this error on shutdown:

```
ERROR - Database 'C:/Users/Win10/openLCA-data-1.4/databases/proto' not found.
java.sql.SQLException: Database 'C:/Users/Win10/openLCA-data-1.4/databases/proto' not found.
        at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
        at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
        at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
        at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
        at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
        at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
        at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
        at org.openlca.core.database.derby.DerbyDatabase.close(DerbyDatabase.java:187)
        at org.openlca.proto.server.Server.lambda$main$1(Server.java:105)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: ERROR XJ004: Database 'C:/Users/Win10/openLCA-data-1.4/databases/proto' not found.
        at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
        at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
        ... 19 more
```

maybe the reason is the shutdown-hook?